### ISSUE TITLE
Update results in theming errors

### ISSUE THREAD

**Issue by patrickTingen** [jcaillon/3P#182]
### Description of the Issue
I updated to v1.7.6, restarted and got this message:
![3P setup message](https://imgur.com/9ETLcsx.png)

and a couple of errors, see below for debug log, see [screenshot](https://imgur.com/ovv1qnm.png) 
I reverted to a saved copy of the themes, but this did not help much. My themes are now more or less corrupted. I changed the default themes and it seems that they got reverted to the standard themes. 

### Debug Information

```Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : D:\Data\DropBox\Apps\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : 3P.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll XMLTools.dll 

============================================================
WHAT : Error in beNotified : code = 1010 : Object reference not set to an instance of an object.
WHEN : 25-10-2017 8:37:47
WHERE : _3PA.MainFeatures.SyntaxHighlighting.ScintillaTheme.SetFontStyle(), line 177
DETAILS : 
    System.NullReferenceException: Object reference not set to an instance of an object.
    at _3PA.MainFeatures.SyntaxHighlighting.ScintillaTheme.SetFontStyle(Byte styleNumber, StyleThemeItem styleItem) in c:\projects\3p\3PA\MainFeatures\SyntaxHighlighting\ScintillaTheme.cs:line 177
    at _3PA.MainFeatures.SyntaxHighlighting.ScintillaTheme.SetScintillaStyles() in c:\projects\3p\3PA\MainFeatures\SyntaxHighlighting\ScintillaTheme.cs:line 134
    at _3PA.Plug.ApplyPluginOptionsForScintilla() in c:\projects\3p\3PA\Plug.cs:line 815
    at _3PA.Plug.ApplyOptionsForScintilla() in c:\projects\3p\3PA\Plug.cs:line 794
    at _3PA.Plug.DoNppBufferActivated(Boolean initiating) in c:\projects\3p\3PA\Plug.cs:line 496
    at _3PA.NppCore.NotificationsPublisher.NppBufferActivated() in c:\projects\3p\3PA\NppCore\NotificationsPublisher.cs:line 264
    at _3PA.NppCore.NotificationsPublisher.OnNppNotification(SCNotification nc) in c:\projects\3p\3PA\NppCore\NotificationsPublisher.cs:line 198


============================================================
WHAT : Error in NotifyUnique : No UIThread!
WHEN : 25-10-2017 8:38:13
WHERE : 6BF5486BA2F867931EBFA34E983B26E8, line 0
DETAILS : 
    System.Exception: No UIThread!


============================================================
WHAT : Loading a theme : Styles definition, couldn't find the styles of the field : <Preprocessor> for the theme <Moonrise> : 
WHEN : 25-10-2017 8:40:45
WHERE : _3PA.MainFeatures.SyntaxHighlighting.ScintillaTheme.<SetColorValues>b__1(), line 248
DETAILS : 
    System.Exception: Styles definition, couldn't find the styles of the field : <Preprocessor> for the theme <Moonrise> :
    at _3PA.MainFeatures.SyntaxHighlighting.ScintillaTheme.<SetColorValues>b__1(String name, SciStyleId enumVal) in c:\projects\3p\3PA\MainFeatures\SyntaxHighlighting\ScintillaTheme.cs:line 248
    at _3PA.Lib.Extensions.ForEach[T](Type curType, Action`2 actionForEachNameValue) in c:\projects\3p\3PA\Lib\Extensions.cs:line 227
    at _3PA.MainFeatures.SyntaxHighlighting.ScintillaTheme.SetColorValues(Type thisType) in c:\projects\3p\3PA\MainFeatures\SyntaxHighlighting\ScintillaTheme.cs:line 246
    at _3PA.MainFeatures.SyntaxHighlighting.ScintillaTheme.set_CurrentTheme(ScintillaTheme value) in c:\projects\3p\3PA\MainFeatures\SyntaxHighlighting\ScintillaTheme.cs:line 57

**Comment by jcaillon** [comment]
Hi Patrick, totally my bad. I changed the name of certain items to be more coherent (for instance appbuilder became preprocessor). I honestly thought no one actually did export and modified those themes. My

**Comment by jcaillon** [comment]
Bad (writing on my phone I pressed close by mistake!).
To unlock the situation, go to appdata/notepad++/plugins/config/3p/ and rename a file named syntaxe. Conf or theme. Conf (I'll check once at work). You will then use the new format on your next startup 
sorry for the inconvenience

**Comment by patrickTingen** [comment]
Hi Julien, thanks for the fast response. I cannot find a file with the name you mentioned, so I'll wait. I switched to the default theme and although it's a bit light to the eyes, at least it works :)

**Comment by jcaillon** [comment]
The first answer was fast but the second... Sorry it was a very busy day.

The conf file is actually in Themes/_ThemesForSyntax.conf. If you had a custom one,  rename it. Then go to Options > Share Export config > click the export button for the syntax highlighting theme. You can then compare the default file to yours and put back your modifications.

I also find the default syntax too bright, I personally use the `Default Alt`

Best regads

**Comment by patrickTingen** [comment]
Hi Julien,

No problem, I’ll check it out tomorrow morning


Gr
Patrick

**Comment by patrickTingen** [comment]
Thanks for the instructions; it works and now I have [my own colors](https://imgur.com/mVnS56K) back.
