### ISSUE TITLE
Crash during shutdown due to modified collection

### ISSUE THREAD

**Issue by santoch** [jcaillon/3P#250]
Description:
This is happening somewhat often for me now.  When I go to close np++, it throws up the error dialog and points me to the error log.  The entries look like this:

============================================================
WHAT : Error when saving settings : Collection was modified; enumeration operation may not execute.
WHEN : 2/2/2019 1:32:03 PM
WHERE : System.ThrowHelper.ThrowInvalidOperationException(), line 0
DETAILS : 
    System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
    at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
    at _3PA.Lib.Object2Xml`1.DictToXml(Dictionary`2 inputDict, String elmName, String subElmName, Boolean valueInAttribute) in c:\projects\3p\3PA\Lib\Object2Xml.cs:line 246
    at _3PA.Lib.Object2Xml`1.SaveToXElement(T item, Boolean valueInAttribute) in c:\projects\3p\3PA\Lib\Object2Xml.cs:line 105
    at _3PA.Lib.Object2Xml`1.SaveToXDocument(List`1 instance, Boolean valueInAttribute) in c:\projects\3p\3PA\Lib\Object2Xml.cs:line 82
    at _3PA.Lib.Object2Xml`1.SaveToFile(List`1 instance, String filename, Boolean valueInAttribute) in c:\projects\3p\3PA\Lib\Object2Xml.cs:line 67
    at _3PA.Lib.Object2Xml`1.SaveToFile(T instance, String filename, Boolean valueInAttribute) in c:\projects\3p\3PA\Lib\Object2Xml.cs:line 56
    at _3PA.MainFeatures.Config.Save() in c:\projects\3p\3PA\MainFeatures\Config.cs:line 856

### Steps to Reproduce the Issue

open a bunch of files
close npp

### Expected Behavior
clean shutdown

### Actual Behavior
error dialog

### Screenshots
nothing special

### Debug Information
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 3P.dll ComparePlugin.dll HTMLTag_unicode.dll JSMinNPP.dll NppColumnSort.dll NPPJSONViewer-win32.dll PluginManager.dll SpellChecker.dll VisualStudioLineCopy.Unicode.dll XBrackets.dll XMLTools.dll

**Comment by jcaillon** [comment]
Hi, no idea what is the root cause of this issue but I can fix the exception you are having.

Can you try this intermediate release and tell me if it fixes your message?

https://ci.appveyor.com/api/buildjobs/3hlkrhor5e4o9jn9/artifacts/Releases%2F3P.zip

**Comment by santoch** [comment]
Thanks. I will try this when I get home from work
